# local chat search box
# measured in blocks (can be fractional value)
local-chat-radius: 10

local-chat:
  layout: "[&el&r] <&7%player%&r> %message%"
  on-command: false
  on-prefix: false
  prefix: ""

global-chat:
  layout: "[&cg&r] <&7%player%&r> %message%"
  on-command: true
  on-prefix: true
  prefix: "!!"

default-chat: "local"
