name: LocalChats
version: "${version}"
main: me.boggerbyte.localchats.Main
api-version: 1.18
authors: [ BoggerByte ]
description: You're can see players messages based on how far away are they from you

commands:
  local:
    aliases: [ l ]
    description: "Send message for players that are nearby"
    usage: "/<command> Message that only nearby players will see"
    permission: local-chats.local
  global:
    aliases: [ g ]
    description: "Send message for all players in current world"
    usage: "/<command> Message that whole server will see"
    permission: local-chats.global

permissions:
  local-chats.local:
    description: Use the local command
  local-chats.global:
    description: Use the global command
